### ISSUE TITLE
Dio version 3

### ISSUE THREAD

**Issue by stwonary** [Instabug/Instabug-Dio-Interceptor#4]
Please add Dio version 3 support. thank you
```
Because every version of instabug_dio_interceptor depends on dio ^2.1.7 and module depends on dio ^3.0.9, instabug_dio_interceptor is forbidden.
```

**Comment by ArneSaknussemm89** [comment]
I've actually submitted a PR for doing that here https://github.com/Instabug/Instabug-Dio-Interceptor/pull/3.

I also forked it here with the changes https://github.com/ArneSaknussemm89/Instabug-Dio-Interceptor/tree/dio3-support.

Been using it for the past few weeks.

**Comment by JoseGeorges8** [comment]
@ArneSaknussemm89 Your fork (and the original) is throwing an exception when I plug it into my dio:

```
flutter: The following ArgumentError was thrown:
flutter: Invalid argument: Instance of 'ResponseBody'
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:404:7)
flutter: #1      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:401:9)
flutter: #2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
flutter: #3      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:399:13)
flutter: #4      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:394:9)
flutter: #5      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:536:18)
flutter: #6      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:151:13)
flutter: #7      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
flutter: #8      NetworkLogger.networkLog (package:instabug_flutter/NetworkLogger.dart:17:27)
```

**Comment by Mishanya840** [comment]
UP

**Comment by AliAbdelfattah** [comment]
Package updated to work with Dio 4.0
